# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('city', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=350)),
                ('link', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('geom', djgeojson.fields.PointField()),
            ],
        ),
    ]
